default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: hauphuong
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: shop_online

test:
  <<: *default
  database: shop_online

production:
  <<: *default
  database: shop_online
